from __future__ import annotations

from typing import List, Protocol, Sequence, runtime_checkable

import numpy as np

from .types import HandCommand, InputSample


@runtime_checkable
class Receiver(Protocol):

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get(self, side: str) -> InputSample: ...


@runtime_checkable
class HandController(Protocol):

    @property
    def joint_names(self) -> List[str]: ...
    def compute(self, sample: InputSample) -> HandCommand: ...


@runtime_checkable
class ArmSolver(Protocol):
    @property
    def nq(self) -> int: ...
    def solve(self, target_pose: np.ndarray) -> np.ndarray: ...
    def fk(self, q: np.ndarray) -> np.ndarray: ...
    def active_joint_names(self) -> List[str]: ...


@runtime_checkable
class GlobalArmSolver(ArmSolver, Protocol):
    def solve_robust(self, target_pose: np.ndarray, **kw) -> np.ndarray: ...
    def pose_error(self, q: np.ndarray, target_pose: np.ndarray) -> tuple: ...
    def sync_state(self, q_current: Sequence[float]) -> None: ...
    @property
    def q_neutral(self) -> np.ndarray: ...
